spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/vendora_db
    username: root
    password: 2465

  jpa:
    hibernate:
      ddl-auto: update

  redis:
    host: localhost
    port: 6379
    database: 0

  mail:
    host: smtp.gmail.com
    port: 587
    username: aswindev2465@gmail.com
    password: iyakblfaxoyfwdmcabc
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true