spring:
  application:
    name: auth-service
  jackson:
    serialization:
      write-dates-as-timestamps: false

    mail:
    host: smtp.gmail.com
    port: 587
    username: aswindev2465@gmail.com
    password: iyakblfaxoyfwdmc
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    hostname: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

keycloak:
  server-url: http://localhost:8080
  realm: vendora
  client-id: vendora-admin-service
  client-secret: eTIk2mbE050tKBx2uEFUaLl5umyKfizV