package com.vendora.notification_service.enums;

public enum ServiceCategory {
    IT_SERVICES, PLUMBING, ELECTRICAL, CLEANING,
    CARPENTRY, PAINTING, AC_REPAIR, APPLIANCE_REPAIR,
    PEST_CONTROL, SALON, MASSAGE, TUTORING,
    PHOTOGRAPHY, CATERING, DRIVING, OTHER
}
