server:
  port: 8084
spring:
  application:
    name: provider-service

  datasource:
    url: jdbc:mysql://localhost:3306/vendora
    username: root
    password: 2465
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 20MB
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: provider-group
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

    properties:
      spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
      spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
      spring.json.trusted.packages: "*"
      spring.json.value.default.type: com.example.provider_service.dto.ReviewCreatedEvent



  jackson:
    serialization:
      write-dates-as-timestamps: false

cloudinary:
  cloud-name: djr53cjzj
  api-key: 673629329379178
  api-secret: 7wU1QpHLEbDF-ZP5bVLMYk4ENRw

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true