name: Infra CI (Keycloak + Kafka)

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Start Infra Services
        run: docker-compose up -d

      - name: Wait for services
        run: sleep 30

      - name: Check running containers
        run: docker ps

      - name: Stop services
        run: docker-compose down